# Generated by Django 4.0.3 on 2024-08-11 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0006_question_is_notice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='is_notice',
        ),
    ]
